image: docker

stages:
  - build
  - test
  - deploy
  - clean

variables:
  PROJECT_NAME: SendPass

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH =~ /^dev-/
      variables:
        ENV: DEV
#    - if: $CI_COMMIT_TAG # deploy prod by tag
#      variables:
#        ENV: PROD
    - if: $CI_COMMIT_BRANCH == "prod" # deploy prod by any commit in main branch
      variables:
        ENV: PROD




build-job:
  stage: build
  environment: $ENV
  script:
    - apk add --no-cache vim git
    - export GIT_SHOW_VERSION="$(git show --no-color --no-patch --decorate | head -n 1)"
    - export COMPOSE_PROJECT_NAME=$(echo "$PROJECT_NAME-$ENV" | awk '{print tolower($0)}')
    - docker-compose --file ./docker-compose/docker-compose.yml
      build --pull
      -- php-fpm base-php-fpm



tests:
  stage: test
  image: alpine
  environment: $ENV
  script:
    - /bin/true




deploy-job:
  stage: deploy
  environment: $ENV
  script:
    - export COMPOSE_PROJECT_NAME=$(echo "$PROJECT_NAME-$ENV" | awk '{print tolower($0)}')
    - docker-compose --file ./docker-compose/docker-compose.yml
      up --detach --remove-orphans
      -- base-php-fpm


clean-job:
  stage: clean
  when: always
  script:
    - /bin/true


