
name: sendpass-prod

secrets:
  env-prod-env:
    file: ./../../SendPass.online-secrets/.env.PROD.env

services:
  base: &base
    build: &base-build
      context: ./..
      dockerfile: ./docker-compose/php-fpm/Dockerfile
      target: nonexistent
      args:
        BUILD_ENV: ${BUILD_ENV:-UNKNOWN}
        BUILD_WRK_USER_ID: ${BUILD_WRK_USER_ID:-UNKNOWN}
        BUILD_WRK_GROUP_ID: ${BUILD_WRK_GROUP_ID:-UNKNOWN}
        BUILD_GIT_SHOW_VERSION: ${BUILD_GIT_SHOW_VERSION:-UNKNOWN}
    environment:
      ENV: ${ENV:-UNKNOWN}
    volumes: [ "./..:/wrkdir/sites/SendPass.online:rw" ]
    extra_hosts: [ "host.docker.internal:host-gateway" ]
    secrets: [ env-prod-env ]
    deploy:
      restart_policy:
        delay: 15s
        window: 15s
        max_attempts: 3
        condition: on-failure

  base-php-fpm:
    <<: *base
    build:
      <<: *base-build
      target: base

  work-php-fpm:
    <<: *base
    build:
      <<: *base-build
      target: work

networks:
  default:
    name: ${COMPOSE_PROJECT_NAME}
    driver: bridge
#    driver_opts:
#      com.docker.network.bridge.name: ${COMPOSE_PROJECT_NAME}
